#!/usr/bin/python3
"""
Django settings for QR_Attendance_System project.

Generated by 'django-admin startproject'
using Django 4.2.5.

For more information on this file,
see Django documentation.
"""

from pathlib import Path
import socket

# Build paths inside the project.
BASE_DIR = Path(__file__).resolve().parent.parent

# Development settings, not for production.
# Checklist for secure deployment.
# See https://docs.djangoproject.com

# Security settings for production.
SECRET_KEY = (
    "django-insecure-%&4dfwaayogd!r)=ot3hi1ybepd=s9d%$gkcomne)rq-a&fnmq"
)

# Debug mode for development only.
DEBUG = True

s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.connect(("8.8.8.8", 80))
ip = s.getsockname()[0]

# Allowed hosts for development.
ALLOWED_HOSTS = ["127.0.0.1", f"{ip}", "localhost"]

# Application definition settings.
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "FacultyView",
    "StudentView",
]

# Middleware configuration settings.
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Root URL configuration setting.
ROOT_URLCONF = "QR_Attendance_System.urls"

# Template engine settings for Django.
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI application settings.
WSGI_APPLICATION = "QR_Attendance_System.wsgi.application"

# Database configuration settings.
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation settings.
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]

# Internationalization settings.
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files configuration settings.
STATIC_URL = "static/"

# Default primary key field settings.
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
